name: Flutter Build Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  buildios:
    name: Build iOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b 1.17.1 _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
      - run: flutter build ios --no-codesign
      - run: git diff --exit-code
  buildandroid:
    name: Build Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b 1.17.1 _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
      - run: flutter build appbundle
      - run: git diff --exit-code
